version: '3'
services:
  forexservice:
    build: ./foreweb
    # command: gunicorn foreweb.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      # - ./.forexservice/:/usr/src/app/
      - ./.forexservice/:/app/
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=foreweb.settings
    networks:
      - payflex_network

  authservice:
    build: ./payflex
    ports:
      - "8002:8000"
    restart: always
    volumes:
      # - ./.authservice/:/usr/src/app/
      - ./.authservice/:/app/
    # command: gunicorn payglen.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=payglen.settings
    networks:
      - payflex_network

  # orderservice:
  #   build: ./walliweb
  #   ports:
  #     - "8003:8000"
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=ordersweb.settings
  #   networks:
  #     - payflex_network

  # flaskservice:
  #   build: ./flask
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - payflex_network


    # environment:
    #   - DJANGO_SETTINGS_MODULE=ordersweb.settings

  # payment_service:
  #   build: ./payment_service
  #   ports:
  #     - "8004:8000"
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=payment_service.settings
  #     networks:
  #       - payflex_network

  nginx:
    # image: nginx:latest
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authservice
      - forexservice
    networks:
      - payflex_network

# networks:
#   payflex_network:
#     external: true

networks:
  payflex_network:


volumes:
  .authservice:
  .forexservice: