# Generated by Django 5.1.1 on 2024-09-05 12:48

import django_resized.forms
import news.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='post/post.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[1024, 768], upload_to=news.utils.user_directory_path),
        ),
    ]
