# Generated by Django 5.0.4 on 2024-08-28 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='image',
            field=models.FileField(default='vehicle/car_image.svg', upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
