# Generated by Django 5.0.4 on 2024-08-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
