# Generated by Django 5.0.4 on 2024-04-30 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0003_alter_carmodel_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=250, unique=True),
        ),
    ]
