# Generated by Django 5.0.4 on 2024-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0004_alter_vehicle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='drive_type',
            field=models.CharField(default='Aspirated', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='engine_config',
            field=models.CharField(default='In-line', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='engine_location',
            field=models.CharField(default='Aspirated', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='fuel_injection',
            field=models.CharField(default='Direct Injection', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='induction',
            field=models.CharField(default='Aspirated', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='power',
            field=models.CharField(default='140 kw ', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='torque',
            field=models.CharField(default='7000 rpm', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='valve_gear',
            field=models.CharField(default='DOHC with VVT', max_length=254),
        ),
    ]
