# Generated by Django 5.0.4 on 2024-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0005_alter_vehicleotherfeatures_drive_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='global_safety_rating',
            field=models.CharField(default='G NCAP Rating', help_text='Global NCAP Safety Rating', max_length=254),
        ),
    ]
