# Generated by Django 5.0.4 on 2024-05-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0006_alter_vehicleotherfeatures_global_safety_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclekeyfeatures',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='tradings.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_features', to='tradings.vehicle'),
        ),
    ]
