# Generated by Django 5.0.4 on 2024-05-12 16:28

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0007_alter_vehiclekeyfeatures_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleotherfeatures',
            options={'verbose_name': 'EngineFeature', 'verbose_name_plural': 'EngineFeatures'},
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1440, 1080], upload_to='car/photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2020, verbose_name='year'),
        ),
    ]
