# Generated by Django 5.0.4 on 2024-05-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0008_alter_vehicleotherfeatures_options_alter_image_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sold', 'Sold'), ('pending', 'Pending'), ('published', 'Published')], default='draft', max_length=100),
        ),
    ]
