# Generated by Django 5.0.4 on 2024-05-13 17:08

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0009_alter_vehicle_options_vehicle_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name'], 'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ['name'], 'verbose_name': 'Make', 'verbose_name_plural': 'Makes'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='vehicle/car.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1440, 1080], upload_to='vehicle/photos/%Y/%m/%d/'),
        ),
    ]
