# Generated by Django 5.0.4 on 2024-05-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0010_alter_carmodel_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleotherfeatures',
            name='body_type',
            field=models.CharField(default='Hatchback', max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='drive_type',
            field=models.CharField(default='FWD', max_length=254),
        ),
    ]
