# Generated by Django 5.0.4 on 2024-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0013_alter_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('suv', 'SUV'), ('bus', 'Bus'), ('truck', 'Truck'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('minivan', 'Minivan'), ('crossover', 'Crossover'), ('hatchback', 'Hatchback'), ('sportscar', 'Sports car'), ('convertible', 'Convertible'), ('pickuptruck', 'Pickup Truck'), ('stationwagon', 'Station Wagon')], default='draft', max_length=100),
        ),
    ]
