# Generated by Django 5.0.4 on 2024-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0014_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('suv', 'SUV'), ('bus', 'Bus'), ('truck', 'Truck'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('minivan', 'Minivan'), ('crossover', 'Crossover'), ('hatchback', 'Hatchback'), ('sportscar', 'Sports car'), ('convertible', 'Convertible'), ('pickuptruck', 'Pickup Truck'), ('stationwagon', 'Station Wagon')], default='sedan', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='body_type',
            field=models.CharField(choices=[('suv', 'SUV'), ('bus', 'Bus'), ('truck', 'Truck'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('minivan', 'Minivan'), ('crossover', 'Crossover'), ('hatchback', 'Hatchback'), ('sportscar', 'Sports car'), ('convertible', 'Convertible'), ('pickuptruck', 'Pickup Truck'), ('stationwagon', 'Station Wagon')], default='Hatchback', max_length=254),
        ),
    ]
