# Generated by Django 5.0.4 on 2024-08-05 11:39

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0015_alter_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[882, 484], upload_to='car/photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='vehicle/car.jpg', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[882, 484], upload_to='vehicle/photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('suv', 'SUV'), ('bus', 'Bus'), ('truck', 'Truck'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('bakkie', 'Bakkie'), ('minivan', 'Minivan'), ('crossover', 'Crossover'), ('hatchback', 'Hatchback'), ('sportscar', 'Sports car'), ('convertible', 'Convertible'), ('pickuptruck', 'Pickup Truck'), ('stationwagon', 'Station Wagon')], default='sedan', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleotherfeatures',
            name='body_type',
            field=models.CharField(choices=[('suv', 'SUV'), ('bus', 'Bus'), ('truck', 'Truck'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('bakkie', 'Bakkie'), ('minivan', 'Minivan'), ('crossover', 'Crossover'), ('hatchback', 'Hatchback'), ('sportscar', 'Sports car'), ('convertible', 'Convertible'), ('pickuptruck', 'Pickup Truck'), ('stationwagon', 'Station Wagon')], default='Hatchback', max_length=254),
        ),
    ]
