# Generated by Django 5.0.4 on 2024-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0019_enquiry_created_at_enquiry_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='image',
            name='side',
            field=models.CharField(choices=[('interior', 'interior'), ('exterior', 'exterior'), ('colour', 'Colour')], default='interior', max_length=300),
        ),
    ]
