# Generated by Django 5.0.4 on 2024-08-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0020_alter_enquiry_options_image_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('newcar', 'New Car'), ('usedcar', 'Used Car'), ('democar', 'Demo Car'), ('accidentcar', 'Accident Car')], default='newcar', max_length=100),
        ),
    ]
