# Generated by Django 5.0.4 on 2024-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0021_alter_vehicle_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('new', 'New Car'), ('used', 'Used Car'), ('demo', 'Demo Car'), ('accident', 'Accident Car')], default='new', max_length=100),
        ),
    ]
