# Generated by Django 5.0.4 on 2024-08-05 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0022_alter_vehicle_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='icon',
            field=models.FileField(default='vehicle/tesla.svg', upload_to='icons/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
